from pathlib import Path

import httpx

from agentcad.client import AgentCADClient


def test_python_client_exports_dxf_with_exchange_options(tmp_path: Path):
    captured: dict[str, str] = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured.update(dict(request.url.params))
        assert request.method == "GET"
        assert request.url.path == "/api/v2/documents/doc_dxf/export-v2.dxf"
        return httpx.Response(200, content=b"999\nGenerated by P&ID-Agent\n0\nEOF\n")

    client = AgentCADClient("http://example.test")
    client._client.close()
    client._client = httpx.Client(
        base_url="http://example.test/api/v2",
        transport=httpx.MockTransport(handler),
    )
    destination = tmp_path / "drawing.dxf"
    try:
        result = client.export_dxf(
            "doc_dxf",
            destination,
            export_range="viewport",
            units="m",
            scale=0.001,
            padding=8,
            x=10,
            y=20,
            width=300,
            height=200,
        )
    finally:
        client.close()

    assert result == destination
    assert destination.read_bytes().endswith(b"0\nEOF\n")
    assert captured == {
        "range": "viewport",
        "units": "m",
        "scale": "0.001",
        "padding": "8",
        "x": "10",
        "y": "20",
        "width": "300",
        "height": "200",
    }


def test_generic_client_export_routes_dxf(tmp_path: Path):
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path == "/api/v2/documents/doc_dxf/export-v2.dxf"
        return httpx.Response(200, content=b"0\nEOF\n")

    client = AgentCADClient("http://example.test")
    client._client.close()
    client._client = httpx.Client(
        base_url="http://example.test/api/v2",
        transport=httpx.MockTransport(handler),
    )
    try:
        path = client.export("doc_dxf", "dxf", tmp_path / "generic.dxf")
    finally:
        client.close()
    assert path.read_bytes() == b"0\nEOF\n"
